#!/bin/bash
# Setting Up Wordpress on koding.com for the Digital Marketing Essentials Course

# Install MySQL
kpm install mysql

# Install Wordpress
kpm install wordpress

# Add the following to wp-config
echo "define('FS_METHOD', 'direct');" >> ~/Web/wordpress/wp-config.php

# Download and extract the required plugins
pluginDir=~/Web/wordpress/wp-content/plugins

# Contact Form 7
wget https://downloads.wordpress.org/plugin/contact-form-7.4.1.1.zip
unzip contact-form-7.4.1.1.zip
rm contact-form-7.4.1.1.zip
mv contact-form-7 $pluginDir

# Disqus Comment System
wget https://downloads.wordpress.org/plugin/disqus-comment-system.zip
unzip disqus-comment-system.zip
rm disqus-comment-system.zip
mv disqus-comment-system $pluginDir

# FakerPress
wget https://downloads.wordpress.org/plugin/fakerpress.zip
unzip fakerpress.zip
rm fakerpress.zip
mv fakerpress $pluginDir

# Google XML Sitemaps
wget https://downloads.wordpress.org/plugin/google-sitemap-generator.4.0.8.zip
unzip google-sitemap-generator.4.0.8.zip
rm google-sitemap-generator.4.0.8.zip
mv google-sitemap-generator $pluginDir

# Jetpack
wget https://downloads.wordpress.org/plugin/jetpack.3.4.2.zip
unzip jetpack.3.4.2.zip
rm jetpack.3.4.2.zip
mv jetpack $pluginDir

# MailChimp
wget https://downloads.wordpress.org/plugin/mailchimp-for-wp.2.2.9.zip
unzip mailchimp-for-wp.2.2.9.zip
rm mailchimp-for-wp.2.2.9.zip
mv mailchimp-for-wp $pluginDir

# Wordpress SEO
wget https://downloads.wordpress.org/plugin/wordpress-seo.2.0.1.zip
unzip wordpress-seo.2.0.1.zip
rm wordpress-seo.2.0.1.zip
mv wordpress-seo $pluginDir

# WP Super Cache
wget https://downloads.wordpress.org/plugin/wp-super-cache.1.4.4.zip
unzip wp-super-cache.1.4.4.zip
rm wp-super-cache.1.4.4.zip
mv wp-super-cache $pluginDir

# Download and extract the required themes
themeDir=~/Web/wordpress/wp-content/themes

wget https://downloads.wordpress.org/theme/esteem.1.2.2.zip
unzip esteem.1.2.2.zip
rm esteem.1.2.2.zip
mv esteem $themeDir

git clone https://github.com/puikinsh/Sparkling.git
mv Sparkling $themeDir

git clone https://github.com/puikinsh/Dazzling.git
mv Dazzling $themeDir

git clone https://github.com/puikinsh/Travelify.git
mv Travelify $themeDir

git clone https://github.com/puikinsh/Unite-Theme.git
mv Unite-Theme $themeDir