#!/bin/bash
# Setting Up Wordpress on koding.com

# Install MySQL
kpm install mysql

# Install Wordpress
kpm install wordpress

# Add the following to wp-config
echo "define('FS_METHOD', 'direct');" >> ~/Web/wordpress/wp-config.php

# Download and extract the required plugins
cd ~/Web/wordpress/wp-content/plugins
